trails/config/routes.rb
Rails.application.routes.draw do
  resources :images
  resources :quotes
  resources :trails
  devise_for :users

  resources :trails do
	resources :quotes, :shallow => true
	resources :images, :shallow => true
  end
  root 'trails#index'

end

trails/app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :trail
  belongs_to :user

  def generate_filename
   require 'securerandom'
   self.filename = SecureRandom.hex(20)
  end

end

trails/app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :user
  belongs_to :trail
end

trails/app/models/trail.rb
class Trail < ActiveRecord::Base
  has_many :quotes, dependent: :destroy
  has_many :images, dependent: :destroy
  #geocoded_by :address
  #after_validation :geocode
end

trails/app/models/user.rb
class User < ActiveRecord::Base
  has_many :quotes
  has_many :images
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

trails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected


  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
  end

end

trails/app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
	 @trail = Trail.find params[:trail_id]
    @image = @trail.images.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
	 @trail = Trail.find params[:trail_id]
    @image = @trail.images.new(image_params)
	 @image.generate_filename
	 @image.user = current_user

    @uploaded_io = params[:image][:uploaded_file]

    File.open(Rails.root.join('public', 'images', @image.filename), 'wb') do |file|
   	 file.write(@uploaded_io.read)
    end
	 

    respond_to do |format|
      if @image.save
        format.html { redirect_to @trail, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:filename, :trail_id, :user_id)
    end
end

trails/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @trail = Trail.find params[:trail_id]
    @quote = @trail.quotes.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @trail = Trail.find params[:trail_id]
    @quote = @trail.quotes.new(quote_params)
    @quote.user = current_user
    
	 respond_to do |format|
      if @quote.save
        format.html { redirect_to @trail, data: { turbolink: true }, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote, :user_id, :trail_id)
    end
end

trails/app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: [:show, :edit, :update, :destroy]
  before_action :set_cache_buster 

  # GET /trails
  # GET /trails.json
  def index
    @trails = Trail.all
  end

  # GET /trails/1
  # GET /trails/1.json
  def show
	   @trail = Trail.find params[:id]
	   @quote = @trail.quotes.new
	   @image = @trail.images.new
		#respond_to do |format|
   		#format.html { redirect_to trails_url }
   		#format.js { render :show_trail }
		#end
	 #redirect_to trails_url
  end

  # GET /trails/new
  def new
    @trail = Trail.new
  end

  # GET /trails/1/edit
  def edit
  end

  # POST /trails
  # POST /trails.json
  def create
    @trail = Trail.new(trail_params)

    respond_to do |format|
      if @trail.save
        format.html { redirect_to @trail, notice: 'Trail was successfully created.' }
        format.json { render :show, status: :created, location: @trail }
      else
        format.html { render :new }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if @trail.update(trail_params)
        format.html { redirect_to @trail, notice: 'Trail was successfully updated.' }
        format.json { render :show, status: :ok, location: @trail }
      else
        format.html { render :edit }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trails/1
  # DELETE /trails/1.json
  def destroy
    @trail.destroy
    respond_to do |format|
      format.html { redirect_to trails_url, notice: 'Trail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_cache_buster
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
end
    # Use callbacks to share common setup or constraints between actions.
    def set_trail
      @trail = Trail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trail_params
      params.require(:trail).permit(:Name, :Description, :StartLng, :StartLat, :EndLng, :EndLat)
    end
end

trails/app/helpers/application_helper.rb
module ApplicationHelper
end

trails/app/helpers/images_helper.rb
module ImagesHelper
end

trails/app/helpers/quotes_helper.rb
module QuotesHelper
end

trails/app/helpers/trails_helper.rb
module TrailsHelper
end

trails/app/views/images/_form.html.erb
<%= form_for([@trail, @image]) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.file_field :uploaded_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trails/app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

trails/app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Trail</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.filename %></td>
        <td><%= image.trail %></td>
        <td><%= image.user %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

trails/app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

trails/app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @image.filename %>
</p>

<p>
  <strong>Trail:</strong>
  <%= @image.trail %>
</p>

<p>
  <strong>User:</strong>
  <%= @image.user %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

trails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div id="user_nav">
	<% if user_signed_in? %>
		Signed in as <%= current_user.email %>. Not you?
		<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Sign up", new_user_registration_path %> or
		<%= link_to "Sign in", new_user_session_path %>
	<% end %>
</div>

<%= yield %>

</body>
</html>

trails/app/views/quotes/_form.html.erb
<%= form_for([@trail, @quote]) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote %><br>
    <%= f.text_field :quote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trails/app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

trails/app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>User</th>
      <th>Trail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.quote %></td>
        <td><%= quote.user %></td>
        <td><%= quote.trail %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

trails/app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

trails/app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @quote.quote %>
</p>

<p>
  <strong>User:</strong>
  <%= @quote.user %>
</p>

<p>
  <strong>Trail:</strong>
  <%= @quote.trail %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>

trails/app/views/trails/_form.html.erb
<%= form_for(@trail) do |f| %>
  <% if @trail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
      <% @trail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :Name %>
  </div>
  <div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :Description, :rows => "10", :cols => "45" %>
  </div>
  <div class="field">
    <%= f.label :StartLng %><br>
    <%= f.number_field :StartLng, :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :StartLat %><br>
    <%= f.number_field :StartLat, :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :EndLng %><br>
    <%= f.number_field :EndLng, :step => 'any' %>
  </div>
  <div class="field">
    <%= f.label :EndLat %><br>
    <%= f.number_field :EndLat, :step => 'any' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trails/app/views/trails/_show.html.erb
<p id="notice"><%= notice %></p>


<div style='width: 90%;'>
    <div id="directions" style='width: 90%; height: 400px;'></div>
</div>

<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();
	function calcRoute() {
     var origin      = new google.maps.LatLng(<%= @trail.StartLat %>, <%= @trail.StartLng %>);
     var destination = new google.maps.LatLng(<%= @trail.EndLat %>, <%= @trail.EndLng %>);
	  var request = {
	      origin:      origin,
	      destination: destination,
	      travelMode:  google.maps.TravelMode.DRIVING
	  };
	  directionsService.route(request, function(response, status) {
	    if (status == google.maps.DirectionsStatus.OK) {
	      directionsDisplay.setDirections(response);
	    }
	  });
	}
	

  calcRoute();
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
  directionsDisplay.setMap(handler.getMap());
});
</script>

<p>
  <strong>Name:</strong>
  <%= @trail.Name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @trail.Description %>
</p>

<p>
  <strong>Startlng:</strong>
  <%= @trail.StartLng %>
</p>

<p>
  <strong>Startlat:</strong>
  <%= @trail.StartLat %>
</p>

<p>
  <strong>Endlng:</strong>
  <%= @trail.EndLng %>
</p>

<p>
  <strong>Endlat:</strong>
  <%= @trail.EndLat %>
</p>

<%= link_to 'Edit', edit_trail_path(@trail) %> |
<%= link_to 'Back', trails_path %>

trails/app/views/trails/edit.html.erb
<h1>Editing Trail</h1>

<%= render 'form' %>

<%= link_to 'Show', @trail %> |
<%= link_to 'Back', trails_path %>

trails/app/views/trails/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Trails</h1>



<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Startlng</th>
      <th>Startlat</th>
      <th>Endlng</th>
      <th>Endlat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trails.each do |trail| %>
      <tr>
			<% @trail = trail %>
        <td><%= trail.Name %></td>
        <td><%= trail.StartLng %></td>
        <td><%= trail.StartLat %></td>
        <td><%= trail.EndLng %></td>
        <td><%= trail.EndLat %></td>
		  <% #render 'show', trail: @trail %>
		  <% #link_to 'Show', request.original_url %>
		  <% #link_to trail.Name, trail, :remote => true, data: { no_turbolink: true } %>
		  <!-- <div id="contenthere"></div> -->
  		  <% @refresh = 0 %>
		  <td><%= link_to 'Show', trail, data: { no_turbolink: true } %></td>
        <td><%= link_to 'Edit', edit_trail_path(trail) %></td>
        <td><%= link_to 'Destroy', trail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trail', new_trail_path %>

trails/app/views/trails/new.html.erb
<h1>New Trail</h1>

<%= render 'form' %>


<%= link_to 'Back', trails_path %>

trails/app/views/trails/show.html.erb
<!DOCTYPE html>
<html>
<head>
<style>

.images {
    display: inline-block;
    text-align: center;
}

</style>
</head>

<p id="notice"><%= notice %></p>

<script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->

<div style='width: 90%;'>
    <div id="directions" style='width: 90%; height: 400px;'></div>
</div>




<p>
  <strong>Name:</strong>
  <%= @trail.Name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @trail.Description %>
</p>

<p>
  <strong>Startlng:</strong>
  <%= @trail.StartLng %>
</p>

<p>
  <strong>Startlat:</strong>
  <%= @trail.StartLat %>
</p>

<p>
  <strong>Endlng:</strong>
  <%= @trail.EndLng %>
</p>

<p>
  <strong>Endlat:</strong>
  <%= @trail.EndLat %>
</p>

<p>
  <% @allusers = User.all %>
  <strong>Quotes:</strong>
  <% @trail.quotes.each do |q| %>
		<% if !q.new_record? %>
			"<%= q.quote  %>"
			-<%= q.user[:name] %><br>
		<% end %>
	<% end %>
</p>


<p>
  <strong>Quotes:</strong>
  <% @trail.images.each do |image| %>
			<% if !image.new_record? %>
		 		<div class="images">
            <%= link_to (image_tag (root_url + "/images/" + image.filename), size: "100x100", alt: image.filename), image %><br>	
				<%= image.user[:name] %>
				</div>
			<% end %>
	<% end %>
</p>



<script type="text/javascript">
var directionsDisplay = new google.maps.DirectionsRenderer();
var directionsService = new google.maps.DirectionsService();
	function calcRoute() {
     var origin      = new google.maps.LatLng(<%= @trail.StartLat %>, <%= @trail.StartLng %>);
     var destination = new google.maps.LatLng(<%= @trail.EndLat %>, <%= @trail.EndLng %>);
	  var request = {
	      origin:      origin,
	      destination: destination,
	      travelMode:  google.maps.TravelMode.DRIVING
	  };
	  directionsService.route(request, function(response, status) {
	    if (status == google.maps.DirectionsStatus.OK) {
	      directionsDisplay.setDirections(response);
	    }
	  });
	}

  calcRoute();
var handler = Gmaps.build('Google');
handler.buildMap({ internal: {id: 'directions'}}, function(){
  directionsDisplay.setMap(handler.getMap());
});
</script>







<% if user_signed_in? %>
	<%= render 'quotes/form' %>
	<%= render 'images/form' %>
<% end %>
<%= link_to 'Edit', edit_trail_path(@trail) %> |
<%= link_to 'Back', trails_path %>
</html>

trails/app/views/trails/show_trail.js.erb
$("#contenthere").html("<%=escape_javascript(render :partial=>"show", trail: @trail)%>");